apiVersion: apps/v1
kind: Deployment
metadata:
  name: fastapi-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: fastapi
  template:
    metadata:
      labels:
        app: fastapi
    spec:
      containers:
      - name: fastapi-container
        image: 000000000000.dkr.ecr.us-east-1.localhost:5100/fastapi-app:75beae9
        ports:
        - containerPort: 8000
