name: Build and Deploy to Kubernetes

on:
  push:
    branches: [main]

jobs:
  build-and-deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout código
        uses: actions/checkout@v4

      - name: Build de la imagen Docker
        run: docker build -t fastapi-app:latest .

      - name: Terraform init y apply (asegura que el ECR existe)
        working-directory: ./terraform
        run: |
          terraform init -backend-config=/home/natalia/terraform-secrets/backend.hcl -reconfigure
          terraform apply -auto-approve -var-file=/home/natalia/terraform-secrets/terraform.tfvars

      - name: Tag y push al ECR emulado
        run: |
          docker tag fastapi-app:latest 000000000000.dkr.ecr.us-east-1.localhost:5100/fastapi-app:latest
          docker push 000000000000.dkr.ecr.us-east-1.localhost:5100/fastapi-app:latest

      - name: Deploy en Kubernetes
        run: |
          kubectl apply -f k8s/deployment.yaml
          kubectl apply -f k8s/service.yaml
          kubectl rollout status deployment/fastapi-deployment
